version: "2"

volumes:
  mysql_data: {}
  redis_data: {}

networks:
  tthnet:
    driver: bridge

services:
  nginx:
    build: .
    # image: 'telkomindonesia/alpine:php-7.1-nginx'
    image: "tth-image:latest"
    networks:
      - tthnet
    user: root
    environment:
      - LARAVEL_SEED_SLEEP=10
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
    volumes:
      - ./:/var/www/data/html
    ports:
      - 4001:8080
    depends_on:
      - mysql_tth
      - redis
    expose:
      - "8080"

  notification:
    build: ./notification
    networks:
      - tthnet
    environment:
      - LARAVEL_SEED_SLEEP=10
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
    volumes:
      - ./notification:/usr/src/app
    ports:
      - 4002:8080
    depends_on:
      - redis
    expose:
      - "8080"

  mysql_tth:
    image: "telkomindonesia/alpine:mysql-10.2"
    user: user
    networks:
      - tthnet
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=bandung
      - MYSQL_ROOT_PASSWORD=bandung
      - MYSQL_DATABASE=dds_db
    ports:
      - 3307:3306
    expose:
      - "3307"
    volumes:
      - mysql_data:/var/lib/mysql/data

  redis:
    image: "telkomindonesia/alpine:redis-3.2"
    ports:
      - 6379:6379
    networks:
      - tthnet
    volumes:
      - redis_data:/var/lib/redis/data
